### ISSUE TITLE
subreddit.banned.add BAD_NUMBER exception if duration is None

### ISSUE THREAD

**Issue by TheVexedGerman** [praw-dev/asyncpraw#15]
**Describe the bug**
When trying to permanently ban a user from a subreddit by either passing None to `duration` or omitting the aforementioned optional parameter an `asyncpraw.exceptions.RedditAPIException: BAD_NUMBER: "that number isn't in the right range (1 to 999)" on field 'duration'` exception is thrown.

**To Reproduce**
1. Create a subreddit object
2. Call the add coroutine on the banned subreddit relationship

**Expected behavior**
The expected behavior is banning the user passed to the coroutine permanently from the subreddit. This behavior would be in line with praw.

**Code/Logs**
Code:
```py
    @commands.command(name='ban')
    async def ban_user(self, ctx, user_name: str, ban_duration: int, ban_reason: str, ban_note: str, ban_message: Optional[str]):
        "Command to ban a user. Duration 0 = permanent"
        subreddit = await self.areddit.subreddit(SUBREDDIT)
        try:
            if ban_duration == 0:
                await subreddit.banned.add(user_name, ban_reason=ban_reason, ban_message=ban_message, note=ban_note)
            else:
                await subreddit.banned.add(user_name, ban_reason=ban_reason, ban_message=ban_message, duration=ban_duration, note=ban_note)
            await ctx.send(f"I've banned {user_name} {'permanently' if ban_duration == 0 else f'for {ban_duration} days'} for you.")
        except:
            await ctx.send(f"```{traceback.format_exc()}```")
```
Logs:
```
Traceback (most recent call last):
  File "/home/user/discord_bot/cogs/reddit_tools.py", line 293, in ban_user
    await subreddit.banned.add(user_name, ban_reason=ban_reason, ban_message=ban_message, note=ban_note)
  File "/home/user/.local/lib/python3.8/site-packages/asyncpraw/models/reddit/subreddit.py", line 2599, in add
    await self.subreddit._reddit.post(url, data=data)
  File "/home/user/.local/lib/python3.8/site-packages/asyncpraw/reddit.py", line 676, in post
    return await self._objectify_request(
  File "/home/user/.local/lib/python3.8/site-packages/asyncpraw/reddit.py", line 584, in _objectify_request
    return self._objector.objectify(
  File "/home/user/.local/lib/python3.8/site-packages/asyncpraw/objector.py", line 180, in objectify
    raise RedditAPIException(errors)
asyncpraw.exceptions.RedditAPIException: BAD_NUMBER: "that number isn't in the right range (1 to 999)" on field 'duration'
```

**System Info**
 - OS: Ubuntu 18.04
 - Python: 3.8.0
 - Async PRAW Version: 7.1.0

**Comment by LilSpazJoekp** [comment]
Testing this with the following:

```py
in[2]: subreddit = await areddit.subreddit('Lil_SpazJoekp')
in[3]: await subreddit.banned.add('Lil_SpazTest', ban_reason='ban_reason', ban_message='ban_message', duration=5, note='ban_note')
in[4]: async for user in subreddit.banned('Lil_SpazTest'):
  ...:     print(user)
  ...:     
Lil_SpazTest
```
The above works while the following does not:

```py
in[5]: subreddit = await areddit.subreddit('Lil_SpazJoekp')
in[6]: await subreddit.banned.add('Lil_SpazTest', ban_reason='ban_reason', ban_message='ban_message', duration=1000, note='ban_note')
```
This returns the same error you have above. Could you be passing a number greater then 999 in to `ban_duration`?

**Comment by TheVexedGerman** [comment]
No I am not passing any number, I am passing nothing for the duration by not specifying it. I've also tried explicitly passing `None` to `duration`. Under regular praw this causes the user to be permanently banned. This is the behavior I'm looking for. For some reason it causes the number exception on duration here.

Basically this set up where anything the same as in your example but the duration being `None`
```py
await subreddit.banned.add('Lil_SpazTest', ban_reason='ban_reason', ban_message='ban_message', duration=None, note='ban_note')
```

**Comment by LilSpazJoekp** [comment]
I see what's going on. This is a bug that arises from differences in the network package used. praw uses `requests` while asyncpraw uses `aiohttp`.

What is happening is `requests` parses the data and drops any params that are `None`. It seems that `aiohttp` does not. There for this is actually a bug with asyncprawcore. I will fix it shortly. In the meantime consider this for a fix:

```py
    @commands.command(name='ban')
    async def ban_user(self, ctx, user_name: str, ban_duration: int, ban_reason: str, ban_note: str,
        ban_message: Optional[str]):
        "Command to ban a user. Duration 0 = permanent"
        subreddit = await self.areddit.subreddit(SUBREDDIT)
        try:
            if 1 <= ban_duration <= 999:
                await subreddit.banned.add(user_name, ban_reason=ban_reason, ban_message=ban_message, duration=ban_duration, note=ban_note)
            else:
                await subreddit.banned.add(user_name, ban_reason=ban_reason, ban_message=ban_message, note=ban_note)
            await ctx.send(f"I've banned {user_name} {f'for {ban_duration} days' if 1 <= ban_duration <= 999 else 'permanently'} for you.")
        except:
            await ctx.send(f"```{traceback.format_exc()}```")
```

**Comment by TheVexedGerman** [comment]
Thank you for looking into it so quick and the suggested workaround.
