### ISSUE TITLE
Cannot submit image posts with 7.6 onwards

### ISSUE THREAD

**Issue by JonSatriani** [praw-dev/asyncpraw#224]
### Describe the Bug

My Discord bot happily posts image submissions with asyncpraw 7.5.0, but in 7.6.0 onwards it does not work.

### Desired Result

An image submission

### Relevant Logs

```shell
Traceback (most recent call last):
      File "C:\Users\jon\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\view.py", line 414, in _scheduled_task
        await item.callback(interaction)
      File [...] line 1939, in callback
        image_post = await rfcoc.submit_image(
      File "C:\Users\jon\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpraw\util\deprecate_args.py", line 51, in wrapped
        return await _wrapper(*args, **kwargs)
      File "C:\Users\jon\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpraw\models\reddit\subreddit.py", line 1330, in submit_image
        image_url, websocket_url = await self._upload_media(
      File "C:\Users\jon\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpraw\models\reddit\subreddit.py", line 763, in _upload_media
        response = await self._read_and_post_media(media_path, upload_url, upload_data)
      File "C:\Users\jon\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpraw\models\reddit\subreddit.py", line 705, in _read_and_post_media
        response = await self._reddit._core._requestor._http.post(
      File "C:\Users\jon\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 950, in post
        self._request(hdrs.METH_POST, url, data=data, **kwargs)
    TypeError: ClientSession._request() got an unexpected keyword argument 'files'
```

### Code to reproduce the bug

```python
rfcoc = await reddit.subreddit('fcoc')
image_post = await rfcoc.submit_image(title=self.trip.reddit_header,image_path=self.trip.reddit_img,flair_id=flair_departure,timeout=10)
```

### My code example does not include the `Reddit()` initialization to prevent credential leakage.

Yes

### This code has previously worked as intended.

Yes

### Operating System/Environment

Debian 10

### Python Version

Python 10

### Async PRAW Version

7.6

### Asyncprawcore Version

2.3

### Anything else?

Neither 7.6 nor 7.6.1 works but 7.5 does.

**Comment by Froggi22** [comment]
Will a hotfix (7.6.2) not be released soon to fix issues like this?

**Comment by LilSpazJoekp** [comment]
My apologies, I thought I made a release for this! I'll do that right now.
