### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name' while streaming

### ISSUE THREAD

**Issue by isFakeAccount** [praw-dev/asyncpraw#234]
### Describe the Bug

I am getting the `AttributeError: 'NoneType' object has no attribute 'name'` when streaming the comments. I first chalked it off to people commenting and deleting immediately, but that is not the case. 

### Desired Result

`comment.author` should not be `None` if the comment is not deleted or removed

### Code to reproduce the bug

```Python
main_logger.info(f"Logged into {await reddit_instance.user.me()} Account.")
    pcm_subreddit = await reddit_instance.subreddit("PoliticalCompassMemes")
    async for comment in pcm_subreddit.stream.comments(skip_existing=True):  # Comment
        if comment.author.name.lower() in [getenv("REDDIT_USERNAME", "basedcount_bot").lower(), "flair-checking-bot"]:
           ^^^^^^^^^^^^^^ throws attribute error
```

### The `Reddit()` initialization in my code example does not include the following parameters to prevent credential leakage: 
`client_secret`, `password`, or `refresh_token`.

- [X] Yes

### Relevant Logs

```Shell
Traceback (most recent call last):
  File "/root/basedcount_bot/basedcount_bot.py", line 39, in wrapper
    await func(reddit_instance, mongo_client)
  File "/root/basedcount_bot/basedcount_bot.py", line 250, in read_comments
    if comment.author.name.lower() in [getenv("REDDIT_USERNAME", "basedcount_bot").lower(), "flair-checking-bot"]:
AttributeError: 'NoneType' object has no attribute 'name'
```

### This code has previously worked as intended.

Yes

### Operating System/Environment

Ubuntu 20.04.5 LTS

### Python Version

3.10.7

### Async PRAW Version

7.6.1

### Asyncprawcore Version

2.3.0

### Anything else?

Now technically speaking, I could check if the author is `None` and skip the comment, but as I mentioned, it is giving an error for comments which should have the author info. If I go the skip route, I might skip over normal comments.

**Comment by isFakeAccount** [comment]
Ok turns out that the user has blocked me. The comment appears in the stream but I can't read any fields.
